version: "3.8"

services:
  fake_sso:
    container_name: cl-fake-sso
    image: node:22-alpine
    ports:
      - 8081:8081
    volumes:
      - ./:/app
    working_dir: /app
    command: "npm start"

networks:
  default:
    name: citizenlab